module.exports = {
     oAuthGoogle: {
      GOOGLE_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_FIREBASE_API_KEY,
      GOOGLE_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_GOOGLE_FIREBASE_AUTH_DOMAIN,
      GOOGLE_OAUTH_PROJECT_ID: process.env.NEXT_PUBLIC_GOOGLE_OAUTH_PROJECT_ID,
      GOOGLE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_GOOGLE_STORAGE_BUCKET,
      GOOGLE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_GOOGLE_MESSAGING_SENDER_ID,
      GOOGLE_OAUTH_APP_ID: process.env.NEXT_PUBLIC_GOOGLE_OAUTH_APP_ID,
      GOOGLE_OAUTH_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GOOGLE_OAUTH_MEASUREMENT_ID
    },
    backendUrl : process.env.NEXT_PUBLIC_BACKEND_URL
  };
  